#!/usr/local/bin/bash

MMBASEpath=/usr/local/org/mmbase
LOGpath=/usr/local/org/mmbase/log

# find all java files
find $MMBASEpath -name '*.java' -print > j

# remove the cruft files
grep -v cruft j > j2

# compile files
jikes -d /tmp/ `cat j2` 2> $LOGpath/compile.log 

# remove temp files
rm j
rm j2

# create the jar
cd /tmp
jar cvf mmbase.jar org
