#!/usr/local/bin/bash
yourpath=/usr/local/install
cd $yourpath/orion
LD_LIBRARY_PATH=/usr/local/algemeen/orion/lib/org/mmbase/util/platform
export LD_LIBRARY_PATH

while [ 1==1 ]; do
echo 'Start at ' `date`
java -Dmmbase.config=$yourpath/orion/org/mmbase/config/default -Dmmbase.htmlroot=$yourpath/orion/default-web-app/ -Dmmbase.outputfile=$yourpath/mmbase.log -jar orion.jar 
done
