#!/usr/local/bin/bash

MMBASEpath=/usr/local/install
ORIONpath=/usr/local/install/orion

cd $ORIONpath
LD_LIBRARY_PATH=$MMBASEpath/org/mmbase/util/platform
export LD_LIBRARY_PATH
export CLASSPATH

while [ 1==1 ]; do
echo 'Starting MMBase at ' `date`
java -Dmmbase.config=$MMBASEpath/org/mmbase/config/default \
     -Dmmbase.htmlroot=$ORIONpath/default-web-app/ \
     -Dmmbase.outputfile=$MMBASEpath/org/mmbase/log/mmbase.log \
	 -jar orion.jar 
done
