#!/usr/local/bin/perl -w


#  Logs and mails CVS changes
#
#  Michiel Meeuwissen - november 2002.
#  $Id: cvsmail,v 1.13 2002-11-08 20:13:18 michiel Exp $

use strict;
use FileHandle;

# argumentoj:
my ($log_filename, $user, $files) = @ARGV;

my @files = split(" ", $files);

my $dir = shift @files;

my $basedir     = "/home/michiel/";
my $toaddress   = "cvs\@mmbase.org";
my $cvs         = "/usr/local/bin/cvs";

my $child;
if ($child = fork()) {
    exit 1; # be 'ready' immediatiely, don't let the commiter wait
} else { 
    sleep 5;
    # mesages are on  STDIN:
    my @message = <stdin>;
    
    # determin user:
    
    my $cvsuser = `whoami`;
    chomp $cvsuser;
    
    #{
#	my ($fil, $oldversion, $newversion) = split(",", $files[0]);
#	my $logline =  `$cvs log -r $fil | grep author:`;
#	if ($logline =~ /author: (.*?);/) {
#	    $cvsuser = $1;
#	}
#    }


	
    # mail subject:
    my $subject = "[MMBASE CVS] ".$dir." ";
    for my $file (@files) {
	$subject .= (split(",", $file))[0] . " ";
    }

    # mail message           
    my $message = "From: $user <$cvsuser\@mmbase.org>\nSubject: $subject\n".join("", @message);
    my $message = "From: $cvsuser <$user\@mmbase.org>\nSubject: $subject\n".join("", @message);


    # also log this message:
    my $logfile = new FileHandle(">>$log_filename");
    
    print $logfile "--------------------------------------------------------\n";
    print $logfile "$user  ". `date`. "\n";
    print $logfile $message;
    print $logfile "\n[$files]\n";
    $logfile->close();
    

    # do the mailing
    my $mail = new FileHandle("|mail -s \"$subject\" $toaddress");
    
    print $mail $message."\n";
    
    unless ($files =~ /New directory/) {
	chdir($basedir.$dir);
	for my $file (@files) {
	    my ($fil, $oldversion, $newversion) = split(",", $file);
	    print $mail "\n\n";
	    if (defined $oldversion) {
		if ($oldversion =~ /NONE/) {
		    print $mail "$fil is new\n\n";
		} else {
		    print $mail `$cvs diff -c2 -b -r$oldversion -r$newversion $fil`;
		}
	    }
	    
	}
    }
    
    $mail->close();
} 

