#!/usr/local/bin/perl -w

#
#  Logs and mails CVS changes
#
#  Michiel Meeuwissen - november 2002.
#

use strict;
use FileHandle;

# argumentoj:
my ($log_filename, $user, $files) = @ARGV;

my @files = split(" ", $files);

my $dir = shift @files;

my $basedir = "/home/michiel/";
my $toaddress     = "michiel\@mmbase.org";

# mail too
my $child;
if ($child = fork()) {
    exit 1; # ok, we are ready
} else { 

# mesagxoj estas je STDIN:
my @message = <stdin>;



# determin user:

my $cvsuser = $user;
{
  my ($fil, $oldversion, $newversion) = split(",", $files[0]);
  my $logline =  `cvs log -r $fil | grep author:`;
  if ($logline =~ /author: (.*)/) {
      $cvsuser = $1;
  }
}




my $message = "From: $cvsuser <$user\@mmbase.org>\n",join("", @message);
my $logfile = new FileHandle(">>$log_filename");

print $logfile "--------------------------------------------------------\n";
print $logfile "$cvsuser  ". `date`. "\n";
print $logfile $message;
print $logfile "\n[$files]\n";
$logfile->close();

    sleep 5;
    my $subject = "[MMBASE CVS] ".$dir." ";
    for my $file (@files) {
	$subject .= (split(",", $file))[0] . " ";
    }

    my $mail = new FileHandle("|mail -s \"$subject\" $toaddress");
    
    print $mail $message."\n";
    
    unless ($files =~ /New directory/) {
	chdir($basedir.$dir);
	for my $file (@files) {
	    my ($fil, $oldversion, $newversion) = split(",", $file);
	    print $mail "\n\n";
	    if (defined $oldversion) {
		if ($oldversion =~ /NONE/) {
		    print $mail "$fil is new\n\n";
		} else {
		    print $mail `cvs diff -c2 -b -r$oldversion -r$newversion $fil`;
		}
	    }
	    
	}
    }
    
    $mail->close();
} 

