<?xml version="1.0"?>
<xsl:stylesheet 
  id="xml2tld"  
  version="1.0"	
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  >

  <!-- Tested with:
    ~/mmbase/head/applications$ java org.apache.xalan.xslt.Process -IN taglib/src/org/mmbase/bridge/jsp/taglib/mmbase-taglib.xml -XSL share/xslt/xml2tld.xslt -PARAM version 2.0 | less
   -->


  <xsl:param name="version">1.2</xsl:param>
  <xsl:param name="uri">http://www.mmbase.org/mmbase-taglib-1.0</xsl:param>
  <xsl:output omit-xml-declaration="yes" method="xml" standalone="no" indent="yes" />

  
  
  <!-- main entry point -->
  <xsl:template match="taglib">
    <taglib>
          <xsl:call-template name="taglib"  />
    </taglib>
  </xsl:template>
  

  <xsl:template name="taglib">
      <xsl:comment>
        This is the MMBase tag library descriptor (http://www.mmbase.org). This file is automaticly generated by
        xml2tld.xslt.
        With params: 
          version=<xsl:value-of select="$version" />
          uri    =<xsl:value-of select="$uri" />

      </xsl:comment>
      <xsl:apply-templates select="tlibversion | jspversion" />
      <xsl:if test="not(jspversion)">
        <jspversion><xsl:value-of select="$version" /></jspversion>
      </xsl:if>
      <xsl:apply-templates select="shortname | uri" />
      <xsl:if test="not(uri)">
        <uri><xsl:value-of select="$uri" /></uri>
      </xsl:if>
      <xsl:apply-templates select="info"/>
      <xsl:if test="$version = '2.0'">
        <xsl:apply-templates select="function" mode="base" />
      </xsl:if>
      <xsl:apply-templates select="tag" mode="base" />    
  </xsl:template>
  
  <xsl:template match="info">
    <info><xsl:value-of select="." /></info>
  </xsl:template>
  
  <xsl:template match="tag" mode="base" >
    <tag>
      <xsl:apply-templates select="name | tagclass | teiclass | bodycontent | info" />
      <xsl:apply-templates select="extends" />
      <xsl:apply-templates select="attribute"/> 
    </tag>
  </xsl:template>

  <xsl:template match="function" mode="base" >
    <function>
      <xsl:apply-templates select="name | description | function-class | function-signature | example" />
      <xsl:apply-templates select="extends" />
      <xsl:apply-templates select="attribute"/> 
    </function>
  </xsl:template>
  
  <xsl:template match="tag|taginterface" mode="extends">
    <xsl:apply-templates select="extends" />
    <xsl:apply-templates select="attribute"/> 
  </xsl:template>
  
  <xsl:template match="attribute">
    <attribute><xsl:apply-templates select="name | required | rtexprvalue" /></attribute>
  </xsl:template>
  
  <xsl:template match="extends">
    <xsl:apply-templates select="/taglib/*[name()='tag' or name()='taginterface']/name[.=current()]/parent::*" mode="extends" />
  </xsl:template>
  
  <xsl:template match="tlibversion|shortname|jspversion|uri|name|tagclass|teiclass|bodycontent|required|rtexprvalue|example|function-class|function-signature">
    <xsl:copy-of select="." />
  </xsl:template>
  
</xsl:stylesheet>
