deploy.jars:
	mvn deploy:deploy-file -DgroupId=org.aselect -DartifactId=aselect-system -Dversion=1.5 -Dpackaging=jar -Dfile=org.aselect.system.jar -Durl=scp://mmbase.org/home/mmweb/web/maven2 -DrepositoryId=mmbase

