//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.09.11 at 05:02:54 PM CEST 
//

package com.finalist.portlets.playlist.dto;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.finalist.cmsc.playlist package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

   private final static QName _DaletReference_QNAME = new QName("", "dalet_reference");
   private final static QName _Tracknr_QNAME = new QName("", "tracknr");
   private final static QName _Title_QNAME = new QName("", "title");
   private final static QName _Artist_QNAME = new QName("", "artist");


   /**
    * Create a new ObjectFactory that can be used to create new instances of
    * schema derived classes for package: com.finalist.cmsc.playlist
    */
   public ObjectFactory() {
   }


   /**
    * Create an instance of {@link Playlist }
    */
   public Playlist createPlaylist() {
      return new Playlist();
   }


   /**
    * Create an instance of {@link MusibaseXmlPlaylistExport }
    */
   public MusibaseXmlPlaylistExport createMusibaseXmlPlaylistExport() {
      return new MusibaseXmlPlaylistExport();
   }


   /**
    * Create an instance of {@link CarrierCode }
    */
   public CarrierCode createCarrierCode() {
      return new CarrierCode();
   }


   /**
    * Create an instance of {@link Item }
    */
   public Item createItem() {
      return new Item();
   }


   /**
    * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
    */
   @XmlElementDecl(namespace = "", name = "dalet_reference")
   public JAXBElement<BigInteger> createDaletReference(BigInteger value) {
      return new JAXBElement<BigInteger>(_DaletReference_QNAME, BigInteger.class, null, value);
   }


   /**
    * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
    */
   @XmlElementDecl(namespace = "", name = "tracknr")
   public JAXBElement<BigInteger> createTracknr(BigInteger value) {
      return new JAXBElement<BigInteger>(_Tracknr_QNAME, BigInteger.class, null, value);
   }


   /**
    * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
    */
   @XmlElementDecl(namespace = "", name = "title")
   public JAXBElement<String> createTitle(String value) {
      return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
   }


   /**
    * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
    */
   @XmlElementDecl(namespace = "", name = "artist")
   public JAXBElement<String> createArtist(String value) {
      return new JAXBElement<String>(_Artist_QNAME, String.class, null, value);
   }

}
