/* Generated by Together */

package org.mmbase.storage.search;

/**
 * A constraint that compares the value of two stepfields. 
 */
public interface CompareFieldsConstraint extends FieldCompareConstraint {
    /**
     * Gets the second associated field. 
     */
    StepField getField2();

    /**
     * Returns a string representation of this CompareFieldsConstraint. 
     * The string representation has the form 
     * "CompareFieldsConstraint(field:&lt;field&gt;, 
     *  casesensitive:&lt;casesensitive&gt;, operator:&lt;operator&gt;,
     *  field2:&lt;field2&gt;)"
     * where 
     * <ul>
     * <li><em>&lt;field&gt;</em> is the field alias returned by 
     *     <code>FieldConstraint#getField().getAlias()</code>
     * <li><em>&lt;casesensitive&gt;</em> is the value returned by
     *     {@link FieldConstraint#isCaseSensitive isCaseSensitive()}
     * <li><em>&lt;operator&gt;</em> is the value returned by
     *     (@link FieldCompareConstraint#getOperator getOperator()}
     * <li><em>&lt;field2&gt;</em> is the field alias returned by
     *     <code>#getField2().getAlias()</code>
     * </ul>
     *
     * @return A string representation of this CompareFieldsConstraint.
     */
    public String toString();

    /** @link dependency 
     * @supplierRole field2*/
    /*#StepField lnkStepField1;*/
}
