/* Generated by Together */

package org.mmbase.storage.search;

/**
 * A constraint that compares a stepfield value with another value.
 * <p>
 * This corresponds with comparison operators <, =, > and LIKE in SQL SELECT-syntax. 
 */
public interface FieldCompareConstraint extends FieldConstraint {
    /**
     * Gets the operator used to compare values. This must be either <code>LESS</code>, <code>EQUAL</code> or <code>GREATER</code>. <code>LIKE</code> is allowed as well when the associated field is of string type.
     */
    int getOperator();

    int LESS = 1;
    int EQUAL = 2;
    int GREATER = 3;
    int LIKE = 4;
}
