/* Generated by Together */

package org.mmbase.storage.search;

/**
 * Exception thrown by the methods that process search queries. 
 */
public class SearchQueryException extends Exception {
    public SearchQueryException() {
        super();
    }

    //javadoc is is inherited
    public SearchQueryException(String s) {
        super(s);
    }
}
