/* Generated by Together */

package org.mmbase.storage.search.implementation;

import java.util.*;
import org.mmbase.module.core.MMObjectBuilder;
import org.mmbase.storage.search.*;

/**
 * Basic implementation.
 * The step alias is equal to the table name, unless it is explicitly set.
 *
 * @author Rob van Maris
 * @version $Revision: 1.2 $
 */
public class BasicStep implements Step {
    
    /** Associated builder. */
    private MMObjectBuilder builder = null;
    
    /** Alias property. */
    private String alias = null;
    
    /**
     * Nodenumber set for nodes to be included (ordered
     * using integer comparison).
     */
    private SortedSet nodes = new TreeSet();
    
    /**
     * Constructor.
     *
     * @param builder The builder.
     * @throws IllegalArgumentException when an invalid argument is supplied.
     */
    // package visibility!
    BasicStep(MMObjectBuilder builder) {
        if (builder == null) {
            throw new IllegalArgumentException(
            "Invalid builder value: " + builder);
        }
        this.builder = builder;
        
        // Alias defaults to table name.
        alias = builder.getTableName();
    }
    
    /**
     * Sets alias property.
     *
     * @param alias The alias property.
     * @throws IllegalArgumentException when an invalid argument is supplied.
     */
    public void setAlias(String alias) {
        if (alias == null || alias.trim().length() == 0) {
            throw new IllegalArgumentException(
            "Invalid alias value: " + alias);
        }
        this.alias = alias;
    }
    
    /**
     * Adds node to nodes.
     *
     * @param nodeNumber The nodenumber of the node.
     * @throws IllegalArgumentException when an invalid argument is supplied.
     */
    public void addNode(int nodeNumber) {
        if (nodeNumber < 0) {
            throw new IllegalArgumentException(
            "Invalid nodeNumber value: " + nodeNumber);
        }
        nodes.add(new Integer(nodeNumber));
    }
    
    // javadoc is inherited
    public String getTableName() {
        return builder.getTableName();
    }
    
    // javadoc is inherited
    public String getAlias() {
        return alias;
    }
    
    // javadoc is inherited
    public SortedSet getNodes() {
        return Collections.unmodifiableSortedSet(nodes);
    }
    
    // javadoc is inherited
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj instanceof Step && !(obj instanceof RelationStep)) {
            Step step = (Step) obj;
            return getTableName().equals(step.getTableName())
            && alias.equals(step.getAlias())
            && nodes.equals(step.getNodes());
        } else {
            return false;
        }
    }
    
    // javadoc is inherited
    public int hashCode() {
        return 41 * builder.getTableName().hashCode()
        + 43 * alias.hashCode() + 47 * nodes.hashCode();
    }
    
    // javadoc is inherited
    public String toString() {
        StringBuffer sb = new StringBuffer("Step(tablename:");
        sb.append(getTableName()).
        append(", alias:").
        append(alias).
        append(", nodes:").
        append(nodes).
        append(")");
        return sb.toString();
    }
    
}
