#!/usr/bin/perl -w
use strict;
use File::Find;

find {
    wanted => sub {
        return if /CVS/;
        return unless /\.xml$/;
        testfile($_);
    },
    no_chdir => 1,
},"src/education/templates/editwizards/data";


sub testfile {
    open FH,"< $_" or die "Can't open $_: $!";
    my $file = $_;
    while (<FH>) {
        for (/wizardname="([^"]+)"/) {
            my $wizardfile = "src/education/templates/editwizards/data/$_.xml";
            
            print "In $file: $_ can't be found\n" unless -f $wizardfile;
            my $s = `find src/education/templates/editwizards -name $_.xml`;
            $s =~ s#src/education/templates/editwizards/data/##;
            $s =~ s#\.xml$##;
            warn "Suggestion: $s" if $s
        }
    }
    close FH;
}

