/* Generated by Together */

package org.mmbase.module.database.search;

import java.util.*;

/**
 * A constraint combining several child constraints, using either logical AND or OR.
 * <p>
 * This corresponds to a AND- or OR-expression in SQL SELECT-syntax. 
 */
public interface CompositeConstraint extends Constraint {
    int LOGICAL_AND = 2;
    int LOGICAL_OR = 1;

    /**
     * Gets the child constraints.
     */
    List getChilds();

    /**
     * Gets the logical operator used to combine the child constraints. This must be either LOGICAL_AND or LOGICAL_OR. 
     */
    int getLogicalOperator();

    /**
     * Compares this constraint to the specified object. The result is 
     * <code>true</code> if and only if the argument is a non-null 
     * CompositeConstraint object representing the same constraint(s).
     * 
     * @param obj The object to compare with.
     * @return <code>true</code> if the objects are equal, 
     * <code>false</code> otherwise.
     */
    public boolean equals(Object obj);
    
    // javadoc is inherited
    public int hashCode();

    /** @link dependency 
     * @label child
     * @supplierRole **/
    /*#Constraint lnkConstraint;*/
}
