/* Generated by Together */

package org.mmbase.module.database.search;

/**
 * A constraint that compares the value of two stepfields. 
 */
public interface CompareFieldsConstraint extends FieldCompareConstraint {
    /**
     * Gets the second associated field. 
     */
    StepField getField2();

    /** @link dependency 
     * @supplierRole field2*/
    /*#StepField lnkStepField1;*/
}
