/* Generated by Together */

package org.mmbase.module.database.search;

import java.util.*;

/**
 * A constraint that restricts the value of a stepfield to be in a specified list of values.
 * <p>
 * This corresponds to the use of "in (...)" in SQL SELECT-syntax. 
 */
public interface FieldValueInConstraint extends FieldConstraint {
    /**
     * Gets the list of values that is specified for this constraint. 
     */
    SortedSet getValues();
}
