/* Generated by Together */

package org.mmbase.module.database.search;

/**
 * A constraint that compares a stepfield value with a fixed value.
 * <p>
 * This corresponds with comparison operators <, =, > and LIKE in SQL SELECT-syntax.
 */
public interface FieldValueConstraint extends FieldCompareConstraint {
    /**
     * Gets the value to compare with. If the associated field type is of string type, when used in combination with the operator <code>LIKE</code>,this may contain the following wildcard characters as well:
     * <ul>
     * <li>% for any string
     * <li>_ for a single character
     * </ul>
     */
    Object getValue();
}
