/* Generated by Together */

package org.mmbase.module.database.search;

/**
 * A constraint on a stepfield.
 */
public interface FieldConstraint extends Constraint {
    /**
     * Gets the associated stepfield. 
     */
    StepField getField();

    /**
     * Tests if a the string comparison is case sensitive. This property is ignored if the associated field is not of string type.
     */
    boolean isCaseSensitive();

    /** @link dependency 
     * @clientRole **/
    /*#StepField lnkStepField;*/
}
