/* Generated by Together */

package org.mmbase.module.database.search;

/**
 * A constraint that tests if a stepfield value is null.
 * <p>
 * This corresponds to IS NULL in SQL SELECT-syntax.
 */
public interface FieldNullConstraint extends FieldConstraint {
}
