/* Generated by Together */

package org.mmbase.module.database.search;

/**
 * A relationstep refers to a table of relations between the previous and next step. Relationstep are used to create a path of related objects.
 * <p>
 * This corresponds to a constraint joining the three tables in SQL SELECT-syntax.
 * <p>
 * Note that tables can also be joined using FieldCompareConstraints.
 */
public interface RelationStep extends Step {
    int DIRECTIONS_SOURCE = 1;
    int DIRECTIONS_DESTINATION = 2;
    int DIRECTIONS_BOTH = 3;

    /**
     * Gets the directionality mode used with this relation. This is one of 
     * <ul>
     * <li>DIRECTIONS_SOURCE
     * <li>DIRECTIONS_DESTINATION
     * <li>DIRECTIONS_BOTH
     * </ul> 
     */
    int getDirectionality();

    /**
     * Gets the previous step. 
     */
    Step getPrevious();

    /**
     * Gets the next step. 
     */
    Step getNext();

    /**
     * Compares this relationstep to the specified object. The result is 
     * <code>true</code> if and only if the argument is a non-null 
     * RelationStep object with the same directionality,
     * associated with the same tablename, 
     * using the same alias and including the same nodes.
     * 
     * @param obj The object to compare with.
     * @return <code>true</code> if the objects are equal, 
     * <code>false</code> otherwise.
     * @see Step#equals
     */
    public boolean equals(Object obj);
    
    // javadoc is inherited
    public int hashCode();

    /** @link dependency 
     * @supplierRole previous*/
    /*#Step lnkStep;*/

    /** @link dependency 
     * @supplierRole next*/
    /*#Step lnkStep1;*/
}
