/* Generated by Together */

package org.mmbase.module.database.search;

/**
 * A sortorder specifies sorting of a single field.
 * <p>
 * This corresponds to use of ORDER BY in SQL SELECT-syntax. 
 */
public interface SortOrder {

    int ORDER_ASCENDING = 1;
    int ORDER_DESCENDING = 2;

    /**
     * Gets the associated field.
     * <p>
     * This corresponds to a fieldname in a "ORDER BY" clause in SQL SELECT-syntax.
     */
    StepField getField();

    /**
     * Gets the sort direction. This is be either ORDER_ASCENDING or ORDER_DESCENDING.
     * <p>
     * This corresponds to the use of ASC and DESC in SQL SELECT-syntax.
     */
    int getDirection();

    /**
     * Compares this sortorder to the specified object. The result is 
     * <code>true</code> if and only if the argument is a non-null 
     * SortOrder object associated with the same field, using the same
     * sort direction.
     * 
     * @param obj The object to compare with.
     * @return <code>true</code> if the objects are equal, 
     * <code>false</code> otherwise.
     */
    public boolean equals(Object obj);
    
    // javadoc is inherited
    public int hashCode();

    /** @link dependency 
     * @clientRole 0-1*/
    /*#StepField lnkStepField;*/

    /** @link dependency 
     * @clientRole **/
    /*#SearchQuery lnkSearchQuery;*/
}
