/* Generated by Together */

package org.mmbase.module.database.search;

import java.util.*;

/**
 * A step refers to a table in a search request. Several steps may refer to the same table, therefore each step has an unique alias to identify it.
 * <p>
 * This corresponds to a table name and alias in SQL SELECT-syntax.
 */
public interface Step {
    /**
     * Gets the name of the table referred to by this step.
     * <p>
     * This corresponds to a table name in SQL SELECT-syntax.
     */
    String getTableName();

    /**
     * Gets the alias associated with this step.
     * <p>
     * This corresponds to a table alias in SQL SELECT-syntax.
     */
    String getAlias();

    /**
     * Gets nodenumbers for nodes that must be included in this step.
     * A null value indicates that no such constraint is applied.
     * <p>
     * This corresponds to a "number IN (....)" constraint in SQL SELECT syntax.
     * <p>
     * Note that this can also be achieved by using a FieldValueInConstraint on the "number" field.
     */
    SortedSet getNodes();

    /**
     * Compares this step to the specified object. The result is 
     * <code>true</code> if and only if the argument is a non-null 
     * Step, but not RelationStep, object associated with the same tablename, 
     * using the same alias and including the same nodes.
     * 
     * @param obj The object to compare with.
     * @return <code>true</code> if the objects are equal, 
     * <code>false</code> otherwise.
     * @see RelationStep#equals
     */
    public boolean equals(Object obj);
    
    // javadoc is inherited
    public int hashCode();

    /** @link dependency 
     * @clientRole **/
    /*#SearchQuery lnkSearchQuery;*/
}
