/* Generated by Together */

package org.mmbase.module.database.search;

/**
 * A stepfield refers to a field in a step.
 *  Each stepfield has an unique alias to identify it.
 * <p>
 * This corresponds to a prefixed fieldname in a SQL SELECT-syntax.
 */
public interface StepField {
    /**
     * Gets the name of the associated field (without prefix).
     * <p>
     * This corresponds to the fieldname in SQL SELECT-syntax.
     */
    String getFieldName();

    /**
     * Gets the alias for the associated field.
     * <p>
     * This corresponds to the field alias in SQL SELECT-syntax. 
     */
    String getAlias();

    /**
     * Gets the step associated with this fieldstep. 
     */
    Step getStep();

    /**
     * Gets the type of the associated field. This is one of the values defined in {@link org.mmbase.module.corebuilders.FieldDefs FieldDefs}.
     */
    int getType();

    /**
     * Compares this stepfield to the specified object. The result is 
     * <code>true</code> if and only if the argument is a non-null 
     * StepField object associated with the same field, using the same alias.
     * 
     * @param obj The object to compare with.
     * @return <code>true</code> if the objects are equal, 
     * <code>false</code> otherwise.
     */
    public boolean equals(Object obj);
    
    // javadoc is inherited
    public int hashCode();

    /** @link dependency 
     * @clientRole **/
    /*# Step lnkStep;*/
}
