#!/usr/bin/perl -w
use strict;

my $printing;

BEGIN { 
  $printing = 0; 
} 


my  ($file, $totrev, $selrev);
while (<>) {
    
    if (/=====/) {
	$printing = 0;
    } 
    
    if (/^Working file: (.*)/) {
	$file = $1;
	#print "WORK $file\n";
    }
    
    if (/^total revisions:(.*?);\s*selected revisions:(.*)/ ) {
	$totrev = $1;
	$selrev = $2;
	#print "tot: $totrev  sel: $selrev\n\n";
	if ($selrev > 0) {
	    $printing = 1;
	    print "\n\n==================================================".
		  "\nFILE: $file\n";
	    next;
	}		
    }
    
    if ($printing) {
        next if /^description:/;
	print;
    }
}
