#!/usr/local/bin/perl -w

#  Logs and mails CVS changes
#
#  @author Michiel Meeuwissen
#  $Id: cvsmail,v 1.4 2003-12-14 13:15:42 michiel Exp $

use strict;
use FileHandle;

# arguments
my ($log_filename, $user, $files, $toaddress) = @ARGV;

# configuration
my $basedir     = "/usr/local/cvs/CVSROOT/log";
my $defaulttoaddress   = "cvs\@mmbase.org";
my $cvs         = "/usr/local/bin/cvs";


if (! defined $files) {
    print "Needs (at least) three arguments\n";
    exit 0;
}

if (! defined $toaddress) {
    $toaddress = $defaulttoaddress;
}

my @files = split(" ", $files);
my $dir = shift @files;


my $child;
if ($child = fork()) {
    exit 0; # be 'ready' immediatiely, don't let the commiter wait
} else { 
    sleep 5;
    # mesages are on  STDIN:
    my @message = <stdin>;
    
    # determin user:
    
    my $cvsuser = `/usr/ucb/whoami`;
    chomp $cvsuser;
    
    #{
#	my ($fil, $oldversion, $newversion) = split(",", $files[0]);
#	my $logline =  `$cvs log -r $fil | grep author:`;
#	if ($logline =~ /author: (.*?);/) {
#	    $cvsuser = $1;
#	}
#    }


	
    # mail subject:
    my $subject = "[MMBASE CVS] ".$dir." ";
    for my $file (@files) {
	$subject .= (split(",", $file))[0] . " ";
    }

    # mail message           
    my $message = "From: $user <wwwtech\@mmbase.org>\nSubject: $subject\n".join("", @message);

    # also log this message:
    my $logfile = new FileHandle(">>$log_filename");
    
    print $logfile "--------------------------------------------------------\n";
    print $logfile "$user ($cvsuser) ". `date`. "\n";
    print $logfile $message;
    print $logfile "\n[$files]\n";
    $logfile->close();
    

    # do the mailing
    if (1) {
	my $mail = new FileHandle("|mail -s \"$subject\" $toaddress");
	
	print $mail $message."\n";
	
	unless ($files =~ /New directory/) {
	    #chdir($basedir.$dir); # why is this necessary?
	    for my $file (@files) {
		my ($fil, $oldversion, $newversion) = split(",", $file);
		print $mail "\n\n";
		if (defined $oldversion) {
		    if ($oldversion =~ /NONE/) {
			print $mail "$fil is new\n\n";
		    } else {
			print $mail `$cvs diff -u -b -r$oldversion -r$newversion $fil`;
		    }
		}
		
	    }
	}
	
	$mail->close();
    }
} 

