/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class setUser */

#ifndef _Included_setUser
#define _Included_setUser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     setUser
 * Method:    setUserGroupNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_setUser_setUserGroupNative
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
